// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://imkkylqpexdgrncgomrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlta2t5bHFwZXhkZ3JuY2dvbXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5Njc5MDAsImV4cCI6MjA4OTU0MzkwMH0.I_X_ZQk0JBhoPfeRyqNrY-JGpvFRYRoKzDcTNCPs8Sk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);